## EDA on Property and Casualty Data

In [74]:
# Here is an explanation of the columns: https://www.kaggle.com/code/zainawan27/exploratorydataanalysisinsurance

In [1]:
# import libraries
import pandas as pd

In [2]:
# Import data
filename = '~/Documents/Software/DevFile/Property&CasualtyInsurance/finalapi.csv'
pdf_data = pd.read_csv(filename)
print(pdf_data.shape)
pdf_data

(213328, 49)

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,RETENTION_POLY_QTY,POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,NB_WRTN_PREM_AMT,...,PL_BOUND_CT_ELINKS,PL_QUO_CT_ELINKS,PL_BOUND_CT_PLRANK,PL_QUO_CT_PLRANK,PL_BOUND_CT_eQTte,PL_QUO_CT_eQTte,PL_BOUND_CT_APPLIED,PL_QUO_CT_APPLIED,PL_BOUND_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW
0,3,3,BOILERMACH,CL,IN,2005,0,0,0,40.00,...,0,0,0,103,50,288,0,0,0,0
1,3,3,BOILERMACH,CL,IN,2006,0,0,0,151.00,...,0,0,0,103,50,288,0,0,0,0
2,3,3,BOILERMACH,CL,IN,2007,0,0,0,40.00,...,0,0,0,103,50,288,0,0,0,0
3,3,3,BOILERMACH,CL,IN,2008,0,0,0,69.00,...,0,0,0,103,50,288,0,0,0,0
4,3,3,BOILERMACH,CL,IN,2009,0,0,0,28.00,...,0,0,0,103,50,288,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213323,9998,9998,PERSUMBREL,PL,IN,2014,39,39,60,0.00,...,0,0,0,0,22,136,0,0,0,0
213324,9998,9998,PERSUMBREL,PL,IN,2015,15,15,18,0.00,...,0,0,0,0,22,136,0,0,0,0
213325,9998,9998,PERSUMBREL,PL,KY,2013,0,9,99999,132.19,...,0,0,0,0,22,136,0,0,0,0
213326,9998,9998,PERSUMBREL,PL,KY,2014,9,12,9,0.00,...,0,0,0,0,22,136,0,0,0,0
213327,9998,9998,PERSUMBREL,PL,KY,2015,5,5,5,0.00,...,0,0,0,0,22,136,0,0,0,0

In [3]:
# Examine the column names, if any nulls, and data types
pdf_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213328 entries, 0 to 213327
Data columns (total 49 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   AGENCY_ID                  213328 non-null  int64
 1   PRIMARY_AGENCY_ID          213328 non-null  int64
 2   PROD_ABBR                  213328 non-null  object
 3   PROD_LINE                  213328 non-null  object
 4   STATE_ABBR                 213328 non-null  object
 5   STAT_PROFILE_DATE_YEAR     213328 non-null  int64
 6   RETENTION_POLY_QTY         213328 non-null  int64
 7   POLY_INFORCE_QTY           213328 non-null  int64
 8   PREV_POLY_INFORCE_QTY      213328 non-null  int64
 9   NB_WRTN_PREM_AMT           213328 non-null  float64
 10  WRTN_PREM_AMT              213328 non-null  float64
 11  PREV_WRTN_PREM_AMT         213328 non-null  float64
 12  PRD_ERND_PREM_AMT          213328 non-null  float64
 13  PRD_INCRD_LOSSES_AMT       213328 non-null  float64
 14  MONTHS                     213328 non-null  int64
 15  RETENTION_RATIO            213328 non-null  float64
 16  LOSS_RATIO                 213328 non-null  float64
 17  LOSS_RATIO_3YR             213328 non-null  float64
 18  GROWTH_RATE_3YR            213328 non-null  float64
 19  AGENCY_APPOINTMENT_YEAR    213328 non-null  int64
 20  ACTIVE_PRODUCERS           213328 non-null  int64
 21  MAX_AGE                    213328 non-null  int64
 22  MIN_AGE                    213328 non-null  int64
 23  VENDOR_IND                 213328 non-null  object
 24  VENDOR                     213328 non-null  object
 25  PL_START_YEAR              213328 non-null  int64
 26  PL_END_YEAR                213328 non-null  int64
 27  COMMISIONS_START_YEAR      213328 non-null  int64
 28  COMMISIONS_END_YEAR        213328 non-null  int64
 29  CL_START_YEAR              213328 non-null  int64
 30  CL_END_YEAR                213328 non-null  int64
 31  ACTIVITY_NOTES_START_YEAR  213328 non-null  int64
 32  ACTIVITY_NOTES_END_YEAR    213328 non-null  int64
 33  CL_BOUND_CT_MDS            213328 non-null  int64
 34  CL_QUO_CT_MDS              213328 non-null  int64
 35  CL_BOUND_CT_SBZ            213328 non-null  int64
 36  CL_QUO_CT_SBZ              213328 non-null  int64
 37  CL_BOUND_CT_eQT            213328 non-null  int64
 38  CL_QUO_CT_eQT              213328 non-null  int64
 39  PL_BOUND_CT_ELINKS         213328 non-null  int64
 40  PL_QUO_CT_ELINKS           213328 non-null  int64
 41  PL_BOUND_CT_PLRANK         213328 non-null  int64
 42  PL_QUO_CT_PLRANK           213328 non-null  int64
 43  PL_BOUND_CT_eQTte          213328 non-null  int64
 44  PL_QUO_CT_eQTte            213328 non-null  int64
 45  PL_BOUND_CT_APPLIED        213328 non-null  int64
 46  PL_QUO_CT_APPLIED          213328 non-null  int64
 47  PL_BOUND_CT_TRANSACTNOW    213328 non-null  int64
 48  PL_QUO_CT_TRANSACTNOW      213328 non-null  int64
dtypes: float64(9), int64(35), object(5)
memory usage: 79.8+ MB

In [4]:
# Examine the numberical columns
pdf_data.describe()

,AGENCY_ID,PRIMARY_AGENCY_ID,STAT_PROFILE_DATE_YEAR,RETENTION_POLY_QTY,POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,PL_BOUND_CT_ELINKS,PL_QUO_CT_ELINKS,PL_BOUND_CT_PLRANK,PL_QUO_CT_PLRANK,PL_BOUND_CT_eQTte,PL_QUO_CT_eQTte,PL_BOUND_CT_APPLIED,PL_QUO_CT_APPLIED,PL_BOUND_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW
count,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,2.133280e+05,2.133280e+05,2.133280e+05,...,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000
mean,4978.964158,21840.982206,2010.191738,158.634525,175.616919,6694.153369,2243.651368,1.963268e+04,2.600812e+04,1.945872e+04,...,26928.162206,26969.472127,26931.800401,27039.756497,26963.478081,27091.403323,26928.081002,26933.596284,26927.300134,26927.453377
std,2928.027642,36410.355440,3.129108,718.766295,774.640860,24639.586044,9976.801667,6.644395e+04,7.008093e+04,6.635115e+04,...,44357.460628,44333.186665,44355.256891,44291.273197,44336.059501,44258.970692,44357.509786,44354.180214,44357.983442,44357.890447
min,3.000000,3.000000,2005.000000,0.000000,0.000000,0.000000,0.000000,-2.027776e+05,-1.861810e+05,-1.643490e+05,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2366.000000,2788.000000,2008.000000,0.000000,0.000000,0.000000,0.000000,2.027500e+00,1.480000e+02,7.600000e+01,...,0.000000,0.000000,0.000000,0.000000,11.000000,66.000000,0.000000,0.000000,0.000000,0.000000
50%,4976.000000,6110.000000,2010.000000,0.000000,0.000000,0.000000,0.000000,1.143620e+03,1.781000e+03,1.180490e+03,...,0.000000,0.000000,0.000000,0.000000,51.000000,258.000000,0.000000,0.000000,0.000000,0.000000
75%,7589.000000,9285.000000,2013.000000,24.000000,30.000000,72.000000,485.000000,8.358695e+03,1.477315e+04,8.231562e+03,...,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000
max,9998.000000,99999.000000,2015.000000,21979.000000,22968.000000,99999.000000,556930.220000,1.715742e+06,1.904570e+06,1.780498e+06,...,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000

Many columns have 9998 or 9999 as their max value. These require more investigation.

In [5]:
# How many unique AGENCY_ID's?

print(f"The number of unique agencies: {pdf_data['AGENCY_ID'].nunique()}")

The number of unique agencies: 1623

In [10]:
# Concatenate the state and agency number (default is duplicated within state)
# pdf_data['AGENCY_ID'].describe()  # Checking the number of digits

pad_width = 6
pdf_data['state_agency'] = pdf_data['STATE_ABBR'].astype(str) +\
pdf_data['AGENCY_ID'].astype(str).str.zfill(pad_width)
print(pdf_data['state_agency'].nunique())

2937

## Investigating 9998 and 9999 values

In [11]:
# Figure out how many 9998 or 9999 values are present in each column.

dct_missing_values = {}

for i in pdf_data:
    dct_missing_values[i] = {}
    dct_missing_values[i]['9998'] = pdf_data[i].isin([9998]).sum().item()
    dct_missing_values[i]['9999'] = pdf_data[i].isin([9999]).sum().item()
    dct_missing_values[i]['99999'] = pdf_data[i].isin([99999]).sum().item()
dct_missing_values

{'AGENCY_ID': {'9998': 342, '9999': 0, '99999': 0},
 'PRIMARY_AGENCY_ID': {'9998': 342, '9999': 0, '99999': 37874},
 'PROD_ABBR': {'9998': 0, '9999': 0, '99999': 0},
 'PROD_LINE': {'9998': 0, '9999': 0, '99999': 0},
 'STATE_ABBR': {'9998': 0, '9999': 0, '99999': 0},
 'STAT_PROFILE_DATE_YEAR': {'9998': 0, '9999': 0, '99999': 0},
 'RETENTION_POLY_QTY': {'9998': 0, '9999': 0, '99999': 0},
 'POLY_INFORCE_QTY': {'9998': 1, '9999': 1, '99999': 0},
 'PREV_POLY_INFORCE_QTY': {'9998': 1, '9999': 1, '99999': 13893},
 'NB_WRTN_PREM_AMT': {'9998': 0, '9999': 1, '99999': 1},
 'WRTN_PREM_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'PREV_WRTN_PREM_AMT': {'9998': 0, '9999': 0, '99999': 13893},
 'PRD_ERND_PREM_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'PRD_INCRD_LOSSES_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'MONTHS': {'9998': 0, '9999': 0, '99999': 0},
 'RETENTION_RATIO': {'9998': 0, '9999': 0, '99999': 129978},
 'LOSS_RATIO': {'9998': 0, '9999': 0, '99999': 51232},
 'LOSS_RATIO_3YR': {'9998': 0, '9999': 0, '99999': 49117},
 'GROWTH_RATE_3YR': {'9998': 0, '9999': 0, '99999': 91067},
 'AGENCY_APPOINTMENT_YEAR': {'9998': 0, '9999': 0, '99999': 5639},
 'ACTIVE_PRODUCERS': {'9998': 0, '9999': 0, '99999': 5639},
 'MAX_AGE': {'9998': 0, '9999': 0, '99999': 5639},
 'MIN_AGE': {'9998': 0, '9999': 0, '99999': 5639},
 'VENDOR_IND': {'9998': 0, '9999': 0, '99999': 0},
 'VENDOR': {'9998': 0, '9999': 0, '99999': 0},
 'PL_START_YEAR': {'9998': 0, '9999': 0, '99999': 82200},
 'PL_END_YEAR': {'9998': 0, '9999': 0, '99999': 209174},
 'COMMISIONS_START_YEAR': {'9998': 0, '9999': 0, '99999': 141937},
 'COMMISIONS_END_YEAR': {'9998': 0, '9999': 0, '99999': 205604},
 'CL_START_YEAR': {'9998': 0, '9999': 0, '99999': 129311},
 'CL_END_YEAR': {'9998': 0, '9999': 0, '99999': 204760},
 'ACTIVITY_NOTES_START_YEAR': {'9998': 0, '9999': 0, '99999': 171536},
 'ACTIVITY_NOTES_END_YEAR': {'9998': 0, '9999': 0, '99999': 209258},
 'CL_BOUND_CT_MDS': {'9998': 0, '9999': 0, '99999': 98689},
 'CL_QUO_CT_MDS': {'9998': 0, '9999': 0, '99999': 98689},
 'CL_BOUND_CT_SBZ': {'9998': 0, '9999': 0, '99999': 98689},
 'CL_QUO_CT_SBZ': {'9998': 0, '9999': 0, '99999': 98689},
 'CL_BOUND_CT_eQT': {'9998': 0, '9999': 0, '99999': 98689},
 'CL_QUO_CT_eQT': {'9998': 0, '9999': 0, '99999': 98689},
 'PL_BOUND_CT_ELINKS': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_QUO_CT_ELINKS': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_BOUND_CT_PLRANK': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_QUO_CT_PLRANK': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_BOUND_CT_eQTte': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_QUO_CT_eQTte': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_BOUND_CT_APPLIED': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_QUO_CT_APPLIED': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_BOUND_CT_TRANSACTNOW': {'9998': 0, '9999': 0, '99999': 57444},
 'PL_QUO_CT_TRANSACTNOW': {'9998': 0, '9999': 0, '99999': 57444},
 'state_agency': {'9998': 0, '9999': 0, '99999': 0}}

In [12]:
# Examine the rows that contain 9999 values
# Turn lines on or off as needed

# pdf_data[pdf_data['PREV_POLY_INFORCE_QTY'] == 9999]
# pdf_data[pdf_data['PREV_POLY_INFORCE_QTY'] == 9998]
pdf_data[pdf_data['NB_WRTN_PREM_AMT'] == 9999]

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,RETENTION_POLY_QTY,POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,NB_WRTN_PREM_AMT,...,PL_QUO_CT_ELINKS,PL_BOUND_CT_PLRANK,PL_QUO_CT_PLRANK,PL_BOUND_CT_eQTte,PL_QUO_CT_eQTte,PL_BOUND_CT_APPLIED,PL_QUO_CT_APPLIED,PL_BOUND_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW,state_agency
17693,811,811,WORKCOMP,CL,KY,2005,0,0,0,9999.0,...,5,0,0,17,78,5,34,0,0,KY000811

### Conclusion Regarding 9998 or 9999 or 99999 values

There does not appear to be very many 9998 or 9999. 
There are many more 99999 values. Replace with NaN.

In [13]:
# Replace rows containing the 9998 or 9999 values
# It's easiest to replace all values with nan and then drop rows containing a null
import numpy as np

print(f"The shape of pdf_data BEFORE inserting nulls: {pdf_data.shape}")

for i in pdf_data:
    pdf_data[i] = pdf_data[i].replace(9998, np.nan)
    pdf_data[i] = pdf_data[i].replace(9999, np.nan)
    pdf_data[i] = pdf_data[i].replace(99999, np.nan)


# pdf_data = pdf_data.dropna()
print(f"The shape of pdf_data AFTER inserting nulls: {pdf_data.shape}")

The shape of pdf_data BEFORE inserting nulls: (213328, 50)
The shape of pdf_data AFTER inserting nulls: (213328, 50)

## Looking for Duplicate Rows

In [14]:
# Looking for duplicates
duplicates = pdf_data.duplicated()
duplicates.sum().item()

0

## Examine the categorical variables

In [15]:
# Examine the categorical variables

l_cat_vars = ['state_agency','PROD_ABBR','PROD_LINE','STATE_ABBR','VENDOR_IND','VENDOR']
dct_unique = {}

# Get a count of each unique value for each of the variables
for i in l_cat_vars:
    dct_unique[i] = {}
    dct_unique[i]['Values'] = pdf_data[i].unique()
    for k in dct_unique[i]['Values']:
        dct_unique[i][k] = len(pdf_data[pdf_data[i]==k])
dct_unique

{'state_agency': {'Values': array(['IN000003', 'KY000003', 'MI000003', ..., 'IN009998', 'KY009998',
         'OH009998'], shape=(2937,), dtype=object),
  'IN000003': 228,
  'KY000003': 193,
  'MI000003': 6,
  'OH000003': 60,
  'PA000003': 19,
  'WV000003': 5,
  'IN000011': 96,
  'WV000011': 3,
  'KY000011': 4,
  'KY000012': 38,
  'IN000012': 7,
  'OH000014': 6,
  'OH000016': 204,
  'WV000016': 62,
  'OH000032': 166,
  'WV000032': 8,
  'PA000036': 130,
  'WV000037': 23,
  'OH000046': 221,
  'PA000046': 5,
  'PA000061': 64,
  'OH000084': 40,
  'OH000087': 208,
  'PA000093': 4,
  'KY000096': 155,
  'KY000099': 14,
  'KY000102': 117,
  'OH000102': 46,
  'WV000102': 30,
  'PA000111': 85,
  'OH000111': 8,
  'PA000123': 8,
  'KY000125': 6,
  'PA000130': 5,
  'MI000134': 4,
  'IN000148': 168,
  'KY000148': 8,
  'OH000152': 221,
  'OH000153': 36,
  'KY000156': 94,
  'MI000156': 7,
  'OH000156': 226,
  'WV000156': 61,
  'IN000156': 9,
  'OH000160': 8,
  'PA000160': 16,
  'OH000163': 47,
  'IN000163': 11,
  'KY000163': 12,
  'IN000164': 16,
  'IN000166': 182,
  'OH000166': 5,
  'PA000166': 4,
  'OH000173': 199,
  'PA000173': 3,
  'KY000184': 87,
  'OH000184': 210,
  'IN000188': 202,
  'PA000204': 178,
  'OH000204': 4,
  'PA000228': 12,
  'PA000237': 42,
  'PA000242': 217,
  'IN000245': 90,
  'OH000245': 146,
  'PA000245': 74,
  'MI000245': 6,
  'OH000251': 125,
  'KY000257': 11,
  'OH000262': 68,
  'KY000263': 173,
  'WV000263': 18,
  'IN000265': 4,
  'IN000279': 19,
  'OH000291': 24,
  'OH000292': 161,
  'IN000294': 177,
  'OH000294': 4,
  'MI000300': 8,
  'IN000301': 182,
  'KY000301': 4,
  'MI000303': 8,
  'PA000307': 120,
  'PA000313': 18,
  'OH000326': 181,
  'IN000330': 24,
  'MI000330': 36,
  'OH000330': 36,
  'KY000348': 12,
  'KY000351': 95,
  'OH000351': 153,
  'IN000351': 7,
  'MI000356': 13,
  'OH000356': 26,
  'KY000364': 8,
  'OH000372': 122,
  'OH000375': 222,
  'IN000375': 9,
  'MI000375': 5,
  'PA000375': 10,
  'OH000390': 52,
  'IN000394': 67,
  'KY000396': 2,
  'OH000401': 126,
  'OH000408': 20,
  'IN000426': 19,
  'PA000448': 119,
  'IN000456': 218,
  'KY000456': 75,
  'OH000456': 116,
  'OH000457': 108,
  'WV000462': 11,
  'OH000463': 56,
  'WV000463': 24,
  'OH000469': 217,
  'WV000469': 204,
  'IN000469': 8,
  'KY000469': 14,
  'PA000469': 4,
  'IN000470': 243,
  'OH000470': 98,
  'KY000470': 11,
  'MI000470': 10,
  'PA000470': 19,
  'MI000477': 40,
  'OH000483': 232,
  'PA000506': 144,
  'KY000507': 203,
  'IN000507': 5,
  'PA000507': 5,
  'OH000512': 207,
  'IN000526': 12,
  'OH000541': 174,
  'KY000541': 8,
  'IN000541': 42,
  'MI000543': 29,
  'KY000548': 12,
  'OH000551': 4,
  'IN000553': 204,
  'MI000553': 9,
  'PA000553': 4,
  'OH000562': 43,
  'PA000562': 231,
  'WV000562': 126,
  'KY000562': 12,
  'IN000562': 4,
  'PA000563': 189,
  'KY000564': 105,
  'PA000578': 185,
  'WV000578': 11,
  'KY000581': 47,
  'OH000586': 236,
  'IN000599': 80,
  'KY000600': 4,
  'IN000604': 139,
  'KY000604': 184,
  'MI000604': 49,
  'OH000604': 209,
  'PA000604': 27,
  'OH000609': 22,
  'OH000618': 16,
  'IN000620': 178,
  'OH000620': 21,
  'PA000625': 15,
  'WV000626': 155,
  'OH000626': 44,
  'IN000633': 81,
  'IN000641': 4,
  'IN000643': 194,
  'OH000643': 45,
  'OH000650': 248,
  'PA000650': 10,
  'MI000650': 7,
  'OH000652': 92,
  'PA000661': 4,
  'KY000663': 71,
  'OH000663': 40,
  'PA000663': 35,
  'IN000667': 20,
  'OH000668': 109,
  'KY000678': 134,
  'IN000678': 16,
  'PA000683': 180,
  'WV000683': 3,
  'IN000683': 2,
  'PA000684': 192,
  'OH000685': 60,
  'IN000685': 11,
  'OH000690': 227,
  'PA000690': 8,
  'IN000690': 12,
  'OH000692': 209,
  'OH000693': 218,
  'MI000693': 4,
  'OH000702': 60,
  'KY000702': 12,
  'IN000702': 4,
  'OH000703': 125,
  'IN000703': 12,
  'WV000716': 131,
  'KY000716': 20,
  'PA000716': 3,
  'PA000726': 130,
  'OH000754': 42,
  'IN000756': 12,
  'OH000770': 181,
  'IN000772': 42,
  'KY000772': 70,
  'MI000772': 62,
  'OH000772': 219,
  'PA000772': 89,
  'WV000772': 41,
  'OH000778': 141,
  'OH000780': 104,
  'PA000787': 74,
  'IN000791': 114,
  'KY000791': 148,
  'OH000791': 46,
  'OH000803': 130,
  'IN000805': 118,
  'OH000805': 17,
  'OH000806': 236,
  'KY000806': 12,
  'WV000808': 82,
  'OH000808': 12,
  'OH000810': 188,
  'IN000811': 146,
  'KY000811': 177,
  'OH000811': 220,
  'PA000811': 4,
  'IN000815': 4,
  'PA000817': 181,
  'OH000831': 12,
  'OH000834': 243,
  'IN000834': 6,
  'PA000834': 7,
  'PA000847': 164,
  'OH000851': 100,
  'PA000859': 205,
  'WV000864': 143,
  'OH000864': 4,
  'IN000865': 36,
  'OH000865': 125,
  'PA000865': 52,
  'WV000865': 32,
  'KY000877': 210,
  'OH000877': 165,
  'IN000877': 58,
  'IN000884': 216,
  'KY000884': 34,
  'IN000885': 168,
  'OH000886': 165,
  'WV000886': 237,
  'MI000886': 2,
  'PA000886': 8,
  'WV000891': 8,
  'OH000897': 207,
  'IN000897': 8,
  'KY000897': 5,
  'PA000897': 6,
  'KY000915': 198,
  'IN000915': 49,
  'OH000917': 4,
  'PA000928': 133,
  'OH000940': 18,
  'OH000949': 227,
  'OH000955': 141,
  'PA000955': 40,
  'KY000962': 11,
  'OH000972': 192,
  'PA000972': 87,
  'MI000976': 21,
  'OH000976': 42,
  'PA000976': 16,
  'IN000983': 165,
  'KY000983': 173,
  'OH000983': 79,
  'WV000983': 20,
  'PA000990': 12,
  'MI000990': 8,
  'IN000993': 124,
  'OH001009': 9,
  'PA001009': 187,
  'WV001009': 26,
  'OH001010': 145,
  'OH001020': 66,
  'MI001022': 67,
  'IN001022': 9,
  'OH001031': 24,
  'OH001040': 51,
  'OH001049': 147,
  'PA001049': 6,
  'IN001049': 30,
  'OH001054': 64,
  'KY001054': 8,
  'PA001057': 154,
  'IN001057': 6,
  'OH001062': 139,
  'OH001074': 16,
  'PA001074': 41,
  'KY001075': 10,
  'IN001079': 188,
  'OH001079': 28,
  'PA001079': 4,
  'OH001091': 36,
  'OH001100': 154,
  'KY001100': 25,
  'IN001100': 7,
  'KY001102': 12,
  'OH001102': 74,
  'PA001126': 212,
  'IN001135': 20,
  'OH001135': 153,
  'WV001135': 2,
  'OH001136': 196,
  'KY001146': 11,
  'OH001160': 8,
  'IN001162': 133,
  'KY001162': 119,
  'OH001162': 231,
  'KY001163': 71,
  'OH001163': 18,
  'WV001169': 4,
  'KY001170': 114,
  'PA001181': 11,
  'WV001183': 86,
  'PA001184': 34,
  'OH001186': 44,
  'KY001189': 202,
  'OH001189': 74,
  'IN001189': 6,
  'OH001191': 200,
  'OH001193': 219,
  'PA001193': 10,
  'KY001193': 3,
  'OH001207': 223,
  'OH001210': 94,
  'WV001210': 142,
  'PA001210': 3,
  'MI001214': 63,
  'IN001214': 2,
  'MI001216': 15,
  'PA001216': 34,
  'PA001224': 32,
  'OH001240': 40,
  'IN001246': 169,
  'KY001246': 24,
  'OH001246': 23,
  'MI001247': 86,
  'OH001247': 16,
  'PA001247': 39,
  'IN001247': 12,
  'KY001247': 8,
  'WV001247': 4,
  'KY001252': 11,
  'IN001262': 49,
  'OH001262': 229,
  'KY001262': 3,
  'WV001262': 15,
  'PA001273': 16,
  'IN001286': 207,
  'OH001287': 7,
  'OH001292': 4,
  'KY001296': 134,
  'KY001297': 199,
  'OH001299': 8,
  'OH001301': 4,
  'MI001303': 15,
  'IN001315': 91,
  'KY001315': 8,
  'MI001315': 52,
  'OH001315': 238,
  'WV001315': 72,
  'OH001342': 102,
  'PA001347': 72,
  'OH001348': 20,
  'OH001355': 22,
  'PA001355': 4,
  'IN001360': 54,
  'OH001378': 215,
  'IN001378': 2,
  'PA001378': 5,
  'WV001378': 6,
  'OH001395': 12,
  'KY001400': 8,
  'OH001400': 36,
  'PA001400': 4,
  'OH001407': 12,
  'IN001409': 22,
  'IN001411': 20,
  'IN001414': 114,
  'KY001414': 100,
  'OH001414': 227,
  'PA001414': 30,
  'WV001414': 43,
  'PA001447': 102,
  'OH001448': 227,
  'IN001448': 4,
  'PA001448': 10,
  'OH001456': 219,
  'PA001456': 62,
  'WV001456': 186,
  'OH001469': 138,
  'OH001478': 121,
  'KY001485': 74,
  'KY001486': 160,
  'KY001489': 140,
  'IN001490': 36,
  'IN001500': 85,
  'MI001500': 28,
  'OH001500': 48,
  'IN001502': 72,
  'OH001504': 178,
  'IN001506': 24,
  'KY001506': 28,
  'OH001506': 4,
  'IN001512': 120,
  'KY001512': 108,
  'OH001512': 217,
  'PA001512': 2,
  'IN001513': 2,
  'IN001525': 22,
  'OH001525': 205,
  'OH001533': 16,
  'IN001536': 17,
  'KY001536': 71,
  'OH001536': 202,
  'IN001541': 87,
  'KY001541': 128,
  'IN001542': 7,
  'PA001544': 5,
  'KY001545': 3,
  'OH001566': 107,
  'MI001569': 14,
  'OH001569': 224,
  'OH001580': 91,
  'IN001582': 90,
  'OH001588': 222,
  'IN001588': 3,
  'PA001588': 6,
  'MI001592': 11,
  'OH001603': 243,
  'PA001603': 9,
  'MI001603': 8,
  'IN001604': 221,
  'OH001606': 60,
  'WV001606': 24,
  'PA001607': 23,
  'KY001609': 78,
  'OH001613': 219,
  'IN001617': 7,
  'IN001620': 57,
  'OH001620': 10,
  'KY001625': 119,
  'OH001625': 3,
  'PA001625': 4,
  'IN001625': 8,
  'PA001631': 11,
  'IN001640': 4,
  'IN001644': 225,
  'KY001653': 11,
  'OH001660': 229,
  'WV001660': 26,
  'PA001660': 36,
  'IN001660': 7,
  'KY001660': 8,
  'OH001662': 237,
  'PA001668': 171,
  'WV001668': 8,
  'IN001668': 4,
  'OH001673': 239,
  'IN001676': 84,
  'OH001676': 39,
  'OH001678': 48,
  'PA001684': 33,
  'OH001687': 11,
  'OH001692': 4,
  'IN001700': 76,
  'KY001700': 160,
  'OH001700': 42,
  'PA001703': 96,
  'OH001712': 35,
  'IN001717': 19,
  'OH001717': 238,
  'PA001717': 38,
  'KY001717': 7,
  'IN001722': 193,
  'PA001722': 16,
  'KY001722': 22,
  'OH001722': 30,
  'WV001722': 2,
  'OH001724': 169,
  'IN001728': 180,
  'KY001728': 25,
  'MI001728': 25,
  'OH001728': 4,
  'KY001729': 68,
  'OH001729': 128,
  'IN001729': 49,
  'OH001732': 4,
  'OH001744': 194,
  'PA001744': 97,
  'MI001744': 4,
  'WV001744': 8,
  'OH001745': 82,
  'PA001760': 24,
  'OH001761': 219,
  'OH001763': 63,
  'OH001771': 230,
  'IN001771': 77,
  'OH001779': 216,
  'IN001779': 102,
  'IN001786': 148,
  'KY001786': 232,
  'OH001786': 177,
  'IN001794': 213,
  'KY001794': 50,
  'KY001797': 4,
  'OH001806': 11,
  'OH001815': 210,
  'PA001815': 5,
  'PA001821': 42,
  'OH001821': 9,
  'KY001826': 100,
  'OH001826': 32,
  'IN001829': 144,
  'KY001829': 140,
  'KY001832': 72,
  'OH001832': 127,
  'PA001836': 135,
  'OH001839': 227,
  'PA001845': 231,
  'KY001847': 169,
  'OH001850': 246,
  'OH001865': 128,
  'IN001865': 7,
  'OH001876': 186,
  'PA001882': 101,
  'OH001882': 5,
  'OH001886': 96,
  'PA001891': 6,
  'OH001898': 5,
  'OH001901': 73,
  'PA001901': 223,
  'WV001901': 13,
  'OH001906': 11,
  'OH001917': 36,
  'OH001919': 4,
  'IN001926': 147,
  'OH001926': 32,
  'IN001938': 84,
  'OH001938': 212,
  'KY001938': 21,
  'IN001939': 214,
  'OH001939': 52,
  'IN001951': 53,
  'OH001951': 233,
  'WV001951': 5,
  'MI001951': 4,
  'PA001951': 4,
  'KY001951': 19,
  'OH001952': 215,
  'IN001953': 30,
  'KY001953': 62,
  'OH001953': 148,
  'PA001953': 31,
  'KY001955': 27,
  'OH001955': 216,
  'KY001958': 119,
  'OH001968': 120,
  'KY001981': 141,
  'OH001981': 224,
  'IN001981': 67,
  'OH001992': 135,
  'IN001992': 8,
  'KY001996': 52,
  'OH001996': 2,
  'OH002006': 175,
  'MI002010': 8,
  'OH002017': 117,
  'OH002021': 6,
  'MI002022': 8,
  'OH002022': 20,
  'PA002022': 2,
  'MI002025': 15,
  'OH002025': 231,
  'PA002025': 2,
  'OH002030': 4,
  'IN002041': 3,
  'MI002041': 32,
  'OH002041': 1,
  'PA002045': 18,
  'OH002049': 229,
  'KY002053': 68,
  'IN002056': 196,
  'MI002056': 1,
  'PA002056': 4,
  'KY002085': 4,
  'OH002089': 56,
  'KY002090': 144,
  'MI002090': 1,
  'OH002093': 47,
  'IN002105': 247,
  'MI002105': 17,
  'OH002105': 94,
  'KY002105': 14,
  'PA002105': 9,
  'OH002109': 229,
  'KY002114': 16,
  'OH002114': 50,
  'WV002114': 91,
  'OH002128': 16,
  'KY002130': 24,
  'IN002131': 59,
  'OH002131': 3,
  'OH002137': 5,
  'PA002137': 11,
  'OH002144': 85,
  'IN002147': 24,
  'KY002147': 29,
  'OH002147': 223,
  'WV002147': 37,
  'PA002147': 4,
  'PA002150': 60,
  'IN002150': 2,
  'IN002189': 59,
  'KY002189': 216,
  'OH002196': 5,
  'KY002213': 40,
  'OH002213': 8,
  'IN002213': 3,
  'OH002214': 47,
  'KY002214': 9,
  'PA002217': 247,
  'KY002219': 12,
  'OH002228': 111,
  'PA002229': 20,
  'OH002232': 227,
  'PA002232': 162,
  'WV002232': 29,
  'IN002237': 77,
  'KY002237': 166,
  'IN002242': 4,
  'IN002244': 214,
  'OH002252': 112,
  'OH002256': 72,
  'KY002257': 177,
  'IN002257': 10,
  'OH002257': 2,
  'IN002260': 40,
  'MI002265': 6,
  'OH002265': 229,
  'IN002265': 18,
  'OH002268': 139,
  'IN002276': 8,
  'OH002279': 141,
  'PA002279': 53,
  'PA002285': 4,
  'WV002288': 36,
  'PA002290': 165,
  'KY002305': 42,
  'MI002305': 61,
  'OH002305': 30,
  'WV002305': 8,
  'IN002305': 4,
  'PA002306': 20,
  'IN002313': 23,
  'KY002313': 158,
  'OH002313': 77,
  'WV002313': 53,
  'PA002313': 4,
  'PA002324': 237,
  'OH002324': 12,
  'PA002332': 8,
  'IN002333': 88,
  'MI002333': 61,
  'OH002343': 130,
  'PA002343': 33,
  'WV002343': 10,
  'KY002352': 10,
  'OH002358': 97,
  'PA002358': 213,
  'IN002358': 11,
  'KY002358': 8,
  'MI002358': 2,
  'WV002358': 6,
  'MI002361': 77,
  'OH002361': 43,
  'IN002363': 139,
  'KY002364': 41,
  'OH002364': 162,
  'WV002364': 227,
  'OH002366': 8,
  'KY002379': 108,
  'OH002379': 189,
  'PA002379': 157,
  'IN002379': 131,
  'MI002379': 60,
  'WV002379': 102,
  'KY002386': 49,
  'OH002393': 228,
  'IN002395': 82,
  'OH002395': 236,
  'KY002395': 23,
  'PA002395': 16,
  'MI002398': 12,
  'OH002398': 56,
  'WV002405': 11,
  'IN002406': 75,
  'OH002406': 32,
  'PA002414': 8,
  'KY002418': 222,
  'IN002418': 8,
  'OH002418': 4,
  'OH002419': 19,
  'OH002429': 195,
  'KY002432': 193,
  'IN002432': 23,
  'OH002444': 68,
  'OH002446': 199,
  'PA002463': 213,
  'IN002463': 6,
  'IN002477': 15,
  'KY002479': 141,
  'WV002479': 8,
  'IN002485': 71,
  'KY002485': 43,
  'OH002485': 218,
  'PA002485': 2,
  'OH002486': 220,
  'IN002486': 3,
  'KY002486': 16,
  'WV002486': 17,
  'MI002486': 6,
  'IN002517': 69,
  'OH002517': 21,
  'KY002519': 195,
  'OH002519': 41,
  'IN002519': 10,
  'PA002523': 190,
  'IN002529': 64,
  'OH002529': 235,
  'IN002530': 8,
  'WV002530': 54,
  'OH002530': 5,
  'PA002533': 9,
  'OH002539': 4,
  'PA002539': 12,
  'OH002549': 24,
  'PA002558': 196,
  'OH002558': 2,
  'WV002558': 1,
  'MI002563': 40,
  'OH002563': 6,
  'OH002565': 219,
  'OH002570': 220,
  'IN002570': 22,
  'KY002570': 8,
  'MI002570': 4,
  'PA002570': 11,
  'WV002570': 7,
  'KY002583': 4,
  'OH002583': 5,
  'OH002586': 43,
  'OH002595': 202,
  'PA002595': 54,
  'IN002595': 69,
  'KY002595': 49,
  'WV002595': 16,
  'IN002606': 108,
  'OH002606': 3,
  'PA002606': 3,
  'OH002613': 70,
  'OH002614': 4,
  'IN002622': 15,
  'OH002622': 33,
  'KY002647': 90,
  'PA002647': 4,
  'IN002651': 162,
  'OH002651': 7,
  'PA002656': 4,
  'OH002657': 9,
  'PA002657': 21,
  'OH002660': 211,
  'IN002660': 5,
  'IN002663': 70,
  'OH002663': 225,
  'KY002663': 12,
  'PA002669': 168,
  'OH002669': 7,
  'OH002674': 114,
  'WV002674': 3,
  'OH002677': 133,
  'WV002677': 240,
  'PA002677': 49,
  'WV002678': 8,
  'OH002688': 8,
  'PA002690': 12,
  'OH002690': 4,
  'MI002711': 35,
  'IN002711': 64,
  'OH002711': 16,
  'OH002722': 67,
  'PA002726': 56,
  'KY002730': 28,
  'PA002741': 183,
  'OH002745': 53,
  'PA002745': 145,
  'WV002745': 86,
  'KY002745': 4,
  'MI002745': 2,
  'IN002745': 4,
  'IN002747': 58,
  'OH002747': 45,
  'KY002747': 5,
  'OH002752': 65,
  'PA002752': 212,
  'IN002757': 77,
  'OH002757': 192,
  'KY002757': 78,
  'OH002776': 202,
  'OH002783': 208,
  'IN002788': 8,
  'OH002788': 206,
  'PA002788': 83,
  'WV002788': 168,
  'OH002800': 48,
  'IN002805': 155,
  'KY002805': 167,
  'OH002805': 236,
  'PA002805': 1,
  'WV002805': 12,
  'KY002826': 4,
  'OH002837': 119,
  'OH002842': 212,
  'PA002842': 46,
  'WV002842': 4,
  'IN002842': 2,
  'OH002843': 18,
  'KY002846': 124,
  'OH002857': 225,
  'KY002857': 5,
  'KY002859': 21,
  'MI002859': 30,
  'OH002859': 196,
  'IN002859': 7,
  'IN002860': 170,
  'MI002860': 37,
  'OH002860': 26,
  'KY002860': 22,
  'PA002860': 4,
  'OH002864': 188,
  'IN002866': 68,
  'IN002868': 4,
  'KY002869': 24,
  'IN002873': 188,
  'OH002873': 115,
  'PA002898': 8,
  'OH002899': 53,
  'PA002899': 56,
  'WV002899': 8,
  'PA002900': 106,
  'KY002902': 33,
  'OH002902': 206,
  'PA002902': 29,
  'WV002902': 25,
  'IN002902': 4,
  'KY002907': 9,
  'OH002907': 9,
  'KY002913': 151,
  'IN002914': 104,
  'MI002914': 32,
  'OH002914': 14,
  'PA002919': 14,
  'KY002938': 18,
  'OH002938': 229,
  'PA002938': 96,
  'WV002938': 33,
  'WV002945': 74,
  'OH002946': 173,
  'OH002970': 42,
  'PA002972': 24,
  'OH002975': 211,
  'OH002988': 4,
  'OH003008': 72,
  'OH003024': 16,
  'PA003031': 62,
  'PA003036': 179,
  'OH003036': 7,
  'KY003036': 2,
  'OH003038': 199,
  'PA003038': 10,
  'WV003038': 72,
  'OH003040': 9,
  'MI003041': 20,
  'IN003048': 4,
  'OH003057': 31,
  'WV003057': 10,
  'PA003057': 4,
  'PA003059': 8,
  'KY003072': 201,
  'OH003072': 4,
  'OH003074': 199,
  'PA003075': 8,
  'IN003076': 72,
  'OH003077': 64,
  'PA003077': 152,
  'WV003077': 27,
  'IN003077': 6,
  'OH003081': 34,
  'OH003089': 11,
  'OH003091': 182,
  'WV003095': 233,
  'IN003095': 5,
  'OH003095': 47,
  'PA003095': 3,
  'KY003095': 11,
  'IN003096': 68,
  'OH003096': 141,
  'KY003096': 9,
  'PA003096': 5,
  'WV003096': 4,
  'MI003096': 11,
  'OH003101': 34,
  'IN003103': 8,
  'OH003104': 186,
  'OH003112': 228,
  'IN003143': 237,
  'KY003143': 145,
  'OH003143': 4,
  'PA003143': 8,
  'PA003145': 4,
  'OH003170': 160,
  'OH003171': 76,
  'OH003177': 73,
  'KY003177': 6,
  'PA003178': 11,
  'OH003182': 5,
  'OH003186': 214,
  'PA003186': 3,
  'IN003186': 7,
  'OH003191': 38,
  'OH003211': 191,
  'KY003211': 53,
  'IN003211': 16,
  'KY003212': 121,
  'IN003212': 11,
  'OH003235': 4,
  'MI003241': 22,
  'OH003241': 5,
  'OH003246': 227,
  'IN003246': 52,
  'OH003262': 16,
  'OH003263': 8,
  'IN003268': 86,
  'IN003275': 16,
  'OH003275': 159,
  'PA003275': 23,
  'KY003275': 3,
  'WV003275': 7,
  'KY003278': 84,
  'OH003278': 15,
  'OH003282': 24,
  'PA003303': 210,
  'WV003303': 15,
  'OH003303': 7,
  'IN003305': 9,
  'OH003311': 190,
  'OH003313': 7,
  'OH003318': 222,
  'OH003325': 159,
  'OH003326': 201,
  'PA003326': 3,
  'OH003332': 170,
  'KY003332': 11,
  'KY003334': 173,
  'IN003334': 5,
  'OH003344': 29,
  'IN003347': 142,
  'KY003347': 200,
  'WV003347': 6,
  'PA003351': 217,
  'IN003354': 20,
  'OH003354': 232,
  'PA003354': 73,
  'WV003354': 55,
  'IN003358': 74,
  'OH003359': 8,
  'KY003360': 205,
  'IN003360': 4,
  'PA003361': 10,
  'OH003370': 197,
  'KY003370': 3,
  'IN003371': 86,
  'OH003371': 21,
  'KY003371': 8,
  'OH003373': 198,
  'KY003373': 71,
  'PA003373': 3,
  ...},
 'PROD_ABBR': {'Values': array(['BOILERMACH', 'BOP', 'COMMAUTO', 'COMMINLMAR', 'COMMPOL',
         'COMMUMBREL', 'CRIME', 'FIREALLIED', 'GARAGE', 'GENERALIAB',
         'WORKCOMP', 'ANNIV', 'ANNIV   12', 'CYCLES', 'DTALK', 'DWELLFIRE',
         'HOMEOWNERS', 'MOBILEHOME', 'MOTORHOM12', 'MOTORHOME',
         'PERSUMBREL', 'YACHT', 'DTALK   12', 'PERSINLMAR', 'SNOWMOBILE',
         'CYCLES  12', 'SNOWMOBI12', 'PERSAIP'], dtype=object),
  'BOILERMACH': 13571,
  'BOP': 9659,
  'COMMAUTO': 14466,
  'COMMINLMAR': 12205,
  'COMMPOL': 13229,
  'COMMUMBREL': 9553,
  'CRIME': 6989,
  'FIREALLIED': 14142,
  'GARAGE': 8397,
  'GENERALIAB': 15254,
  'WORKCOMP': 7227,
  'ANNIV': 13823,
  'ANNIV   12': 3295,
  'CYCLES': 5808,
  'DTALK': 6977,
  'DWELLFIRE': 9735,
  'HOMEOWNERS': 14589,
  'MOBILEHOME': 5739,
  'MOTORHOM12': 1564,
  'MOTORHOME': 8310,
  'PERSUMBREL': 8978,
  'YACHT': 4479,
  'DTALK   12': 737,
  'PERSINLMAR': 2399,
  'SNOWMOBILE': 1233,
  'CYCLES  12': 847,
  'SNOWMOBI12': 62,
  'PERSAIP': 61},
 'PROD_LINE': {'Values': array(['CL', 'PL'], dtype=object),
  'CL': 124692,
  'PL': 88636},
 'STATE_ABBR': {'Values': array(['IN', 'KY', 'MI', 'OH', 'PA', 'WV'], dtype=object),
  'IN': 34923,
  'KY': 29420,
  'MI': 3691,
  'OH': 101323,
  'PA': 32207,
  'WV': 11764},
 'VENDOR_IND': {'Values': array(['N', 'Y'], dtype=object),
  'N': 81402,
  'Y': 131926},
 'VENDOR': {'Values': array(['Unknown', 'C', 'A', 'E', 'G', 'B', 'D', 'H', 'J', 'F'],
        dtype=object),
  'Unknown': 81402,
  'C': 21914,
  'A': 35614,
  'E': 52092,
  'G': 3267,
  'B': 9405,
  'D': 5935,
  'H': 2053,
  'J': 1193,
  'F': 453}}

In [16]:
## Output final dataset

filename = 'agency_performance_final.csv'
pdf_data.to_csv(filename, index=False)